package com.example.worlddata


/**
 * Maps country codes to their themes.
 */
object ThemesMapper {


    /**
     * Returns the theme of the given country code.
     */
    fun getThemeResource(countryCode: String): Int = when (countryCode) {
        "af" -> R.style.Theme_af
        "al" -> R.style.Theme_al
        "dz" -> R.style.Theme_dz
        "ad" -> R.style.Theme_ad
        "ao" -> R.style.Theme_ao
        "ag" -> R.style.Theme_ag
        "ar" -> R.style.Theme_ar
        "am" -> R.style.Theme_am
        "au" -> R.style.Theme_au
        "at" -> R.style.Theme_at
        "az" -> R.style.Theme_az
        "bs" -> R.style.Theme_bs
        "bh" -> R.style.Theme_bh
        "bd" -> R.style.Theme_bd
        "bb" -> R.style.Theme_bb
        "by" -> R.style.Theme_by
        "be" -> R.style.Theme_be
        "bz" -> R.style.Theme_bz
        "bj" -> R.style.Theme_bj
        "bt" -> R.style.Theme_bt
        "bo" -> R.style.Theme_bo
        "ba" -> R.style.Theme_ba
        "bw" -> R.style.Theme_bw
        "br" -> R.style.Theme_br
        "bn" -> R.style.Theme_bn
        "bg" -> R.style.Theme_bg
        "bf" -> R.style.Theme_bf
        "bi" -> R.style.Theme_bi
        "kh" -> R.style.Theme_kh
        "cm" -> R.style.Theme_cm
        "ca" -> R.style.Theme_ca
        "cv" -> R.style.Theme_cv
        "cf" -> R.style.Theme_cf
        "td" -> R.style.Theme_td
        "cl" -> R.style.Theme_cl
        "cn" -> R.style.Theme_cn
        "co" -> R.style.Theme_co
        "km" -> R.style.Theme_km
        "cr" -> R.style.Theme_cr
        "hr" -> R.style.Theme_hr
        "cu" -> R.style.Theme_cu
        "cy" -> R.style.Theme_cy
        "cz" -> R.style.Theme_cz
        "cd" -> R.style.Theme_cd
        "cg" -> R.style.Theme_cg
        "dk" -> R.style.Theme_dk
        "dj" -> R.style.Theme_dj
        "dm" -> R.style.Theme_dm
        "do" -> R.style.Theme_do
        "eg" -> R.style.Theme_eg
        "sv" -> R.style.Theme_sv
        "gq" -> R.style.Theme_gq
        "er" -> R.style.Theme_er
        "ee" -> R.style.Theme_ee
        "sz" -> R.style.Theme_sz
        "et" -> R.style.Theme_et
        "fj" -> R.style.Theme_fj
        "fi" -> R.style.Theme_fi
        "fr" -> R.style.Theme_fr
        "ga" -> R.style.Theme_ga
        "gm" -> R.style.Theme_gm
        "ge" -> R.style.Theme_ge
        "de" -> R.style.Theme_de
        "gh" -> R.style.Theme_gh
        "gr" -> R.style.Theme_gr
        "gd" -> R.style.Theme_gd
        "gt" -> R.style.Theme_gt
        "gn" -> R.style.Theme_gn
        "gw" -> R.style.Theme_gw
        "gy" -> R.style.Theme_gy
        "ht" -> R.style.Theme_ht
        "hn" -> R.style.Theme_hn
        "hu" -> R.style.Theme_hu
        "is" -> R.style.Theme_is
        "in" -> R.style.Theme_in
        "id" -> R.style.Theme_id
        "ir" -> R.style.Theme_ir
        "iq" -> R.style.Theme_iq
        "ie" -> R.style.Theme_ie
        "il" -> R.style.Theme_il
        "it" -> R.style.Theme_it
        "jm" -> R.style.Theme_jm
        "jp" -> R.style.Theme_jp
        "jo" -> R.style.Theme_jo
        "kz" -> R.style.Theme_kz
        "ke" -> R.style.Theme_ke
        "ki" -> R.style.Theme_ki
        "kp" -> R.style.Theme_kp
        "kr" -> R.style.Theme_kr
        "kw" -> R.style.Theme_kw
        "kg" -> R.style.Theme_kg
        "la" -> R.style.Theme_la
        "lv" -> R.style.Theme_lv
        "lb" -> R.style.Theme_lb
        "ls" -> R.style.Theme_ls
        "lr" -> R.style.Theme_lr
        "ly" -> R.style.Theme_ly
        "li" -> R.style.Theme_li
        "lt" -> R.style.Theme_lt
        "lu" -> R.style.Theme_lu
        "mg" -> R.style.Theme_mg
        "mw" -> R.style.Theme_mw
        "my" -> R.style.Theme_my
        "mv" -> R.style.Theme_mv
        "ml" -> R.style.Theme_ml
        "mt" -> R.style.Theme_mt
        "mh" -> R.style.Theme_mh
        "mr" -> R.style.Theme_mr
        "mu" -> R.style.Theme_mu
        "mx" -> R.style.Theme_mx
        "fm" -> R.style.Theme_fm
        "md" -> R.style.Theme_md
        "mc" -> R.style.Theme_mc
        "mn" -> R.style.Theme_mn
        "me" -> R.style.Theme_me
        "ma" -> R.style.Theme_ma
        "mz" -> R.style.Theme_mz
        "mm" -> R.style.Theme_mm
        "na" -> R.style.Theme_na
        "nr" -> R.style.Theme_nr
        "np" -> R.style.Theme_np
        "nl" -> R.style.Theme_nl
        "nz" -> R.style.Theme_nz
        "ni" -> R.style.Theme_ni
        "ne" -> R.style.Theme_ne
        "ng" -> R.style.Theme_ng
        "mk" -> R.style.Theme_mk
        "no" -> R.style.Theme_no
        "om" -> R.style.Theme_om
        "pk" -> R.style.Theme_pk
        "pw" -> R.style.Theme_pw
        "pa" -> R.style.Theme_pa
        "pg" -> R.style.Theme_pg
        "py" -> R.style.Theme_py
        "pe" -> R.style.Theme_pe
        "ph" -> R.style.Theme_ph
        "pl" -> R.style.Theme_pl
        "pt" -> R.style.Theme_pt
        "qa" -> R.style.Theme_qa
        "ro" -> R.style.Theme_ro
        "ru" -> R.style.Theme_ru
        "rw" -> R.style.Theme_rw
        "kn" -> R.style.Theme_kn
        "lc" -> R.style.Theme_lc
        "vc" -> R.style.Theme_vc
        "ws" -> R.style.Theme_ws
        "sm" -> R.style.Theme_sm
        "st" -> R.style.Theme_st
        "sa" -> R.style.Theme_sa
        "sn" -> R.style.Theme_sn
        "rs" -> R.style.Theme_rs
        "sc" -> R.style.Theme_sc
        "sl" -> R.style.Theme_sl
        "sg" -> R.style.Theme_sg
        "sk" -> R.style.Theme_sk
        "si" -> R.style.Theme_si
        "sb" -> R.style.Theme_sb
        "so" -> R.style.Theme_so
        "za" -> R.style.Theme_za
        "ss" -> R.style.Theme_ss
        "es" -> R.style.Theme_es
        "lk" -> R.style.Theme_lk
        "sd" -> R.style.Theme_sd
        "sr" -> R.style.Theme_sr
        "se" -> R.style.Theme_se
        "ch" -> R.style.Theme_ch
        "sy" -> R.style.Theme_sy
        "tw" -> R.style.Theme_tw
        "tj" -> R.style.Theme_tj
        "tz" -> R.style.Theme_tz
        "th" -> R.style.Theme_th
        "tl" -> R.style.Theme_tl
        "tg" -> R.style.Theme_tg
        "to" -> R.style.Theme_to
        "tt" -> R.style.Theme_tt
        "tn" -> R.style.Theme_tn
        "tr" -> R.style.Theme_tr
        "tm" -> R.style.Theme_tm
        "tv" -> R.style.Theme_tv
        "ug" -> R.style.Theme_ug
        "ua" -> R.style.Theme_ua
        "ae" -> R.style.Theme_ae
        "gb" -> R.style.Theme_gb
        "us" -> R.style.Theme_us
        "uy" -> R.style.Theme_uy
        "uz" -> R.style.Theme_uz
        "vu" -> R.style.Theme_vu
        "va" -> R.style.Theme_va
        "ve" -> R.style.Theme_ve
        "vn" -> R.style.Theme_vn
        "eh" -> R.style.Theme_eh
        "ye" -> R.style.Theme_ye
        "zm" -> R.style.Theme_zm
        "zw" -> R.style.Theme_zw
        "ci" -> R.style.Theme_ci
        else -> R.style.Theme_WorldData
    }


}